# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aruljothy
service: graphql-appsync-caller

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  graphqlCaller:
    handler: dist/handler.graphqlCaller
    events:
      - http:
          path: graphql-call
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env
  esbuild:
    bundle: true
    target: "node18"
    platform: node
    sourcemap: true
    outdir: dist
